config/routes.rb
Rails.application.routes.draw do
  
  root 'categories#index'

  resources :categories do
    resources :products do
      resources :reviews
    end
  end

  devise_for :users

  resources :users, only: [:show, :index]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :name, uniqueness: true
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :reviews

  validates :description, :price, :title, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :price, price: true

  paginates_per 15 

  def average_rating
    avg = reviews.any? ? reviews.pluck(:rating).reduce(:+).to_f / reviews.size : 0.0 
    avg.round(2)
  end 

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :rating, :user_id, :content, presence: true
  
  paginates_per 5
  
  scope :most_recent, ->(amount = 10) { order("created_at DESC").limit(amount) }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :firstname, :lastname, :email, presence: true       

  has_many :reviews
  has_many :products


  def is_product_owner?(product)
    self == product.user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # rescue_from ActiveRecord::RecordNotFound, :with => :resource_not_found

  before_action :configure_permitted_parameters, if: :devise_controller?

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protect_from_forgery with: :exception

  def acknowledge_product_owner
    unless current_user.is_product_owner?(product)
      redirect_to(category_product_url(category, product), 
        flash: {:error => 'You are not allowed to edit this product.'})
    end
  end
  
  def approve_admin!
    unless current_user
      redirect_to new_user_session_path, 
        flash: {:error => 'You should be logged as an admin.'}
    end

    unless current_user.admin?
      redirect_admin_to_back flash: {:error => 'You should be logged as an admin.'}
    end
  end

  def current_user
    UserDecorator.decorate(super) unless super.nil?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [ :firstname, :lastname, :about_me ]
    devise_parameter_sanitizer.for(:account_update) << [ :firstname, :lastname, :about_me ]
  end

  private

  def redirect_admin_to_back(default = new_user_session_url, flash: {})
    if !request.env["HTTP_REFERER"].blank? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
      redirect_to :back, flash: flash
    else
      redirect_to default, flash: flash
    end
  end

  def resource_not_found
    redirect_to root_path, flash: {:error => 'Requested resource not found.'}
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :approve_admin!, except: [:index, :show]
  before_action :authenticate_user!

  expose_decorated(:categories)
  expose(:category)
  expose(:product) { Product.new }

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    self.category = Category.new(category_params)

    if category.save
      redirect_to category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if category.update(category_params)
      redirect_to category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  expose(:category)
  expose(:products) { category.products.page params[:page] }
  expose(:product) { params[:id] ? Product.find(params[:id]) : Product.new }
  expose(:review) { Review.new }
  expose_decorated(:reviews, ancestor: :product) { product.reviews.page params[:page] }

  before_action :authenticate_user!
  before_action :acknowledge_product_owner, only: [:edit, :update, :destroy]  

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    params.fetch(:product, []).fetch(:price, '').gsub!(',', '.')
    self.product = Product.new(product_params)
    self.product.user = current_user

    if product.save
      category.products << product
      redirect_to category_product_url(category, product), notice: 'Product was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if self.product.update(product_params)
      redirect_to category_product_url(category, product), notice: 'Product was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /products/1
  def destroy
    product.destroy
    redirect_to category_url(product.category), notice: 'Product was successfully destroyed.'
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  expose(:review)
  expose(:product)
  expose(:category)

  def new
  end

  def edit
  end

  def create

    self.review = Review.new(review_params)
    
    review.user = current_user
    
    if review.save
      product.reviews << review
      redirect_to category_product_url(product.category, product), notice: 'Review was successfully created.'
    else
      category = product.category
      render action: 'new'
    end
  end

  def destroy
    review.destroy
    redirect_to category_product_url(product.category, product), notice: 'Review was successfully destroyed.'
  end

  private
    def review_params
      params.require(:review).permit(:content, :rating, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose_decorated(:users)
  expose_decorated(:user)
  expose_decorated(:recent_reviews, model: :review, 
    decorator: ReviewDecorator) { user.reviews.most_recent(RECENT_USER_REVIEWS) }

  RECENT_USER_REVIEWS = 5
 
  def show
  end

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.haml
= simple_form_for category, html: { class: 'form-horizontal' } do |f|
  .form-group
    = f.label :name, class: 'col-md-3 control-label'
    = f.input :name, label: false, class: 'form-control', wrapper_html: { class: 'col-md-4' }
  .form-group
    .col-md-offset-3
      = f.submit 'Save', class: 'btn btn-default'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', category
\|
= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/index.html.haml
%h1 Listing categories
.row
  .col-md-5.col-md-offset-3
    %table.table.table-hover
      %thead
        %tr
          %th Name
          %th.text-center Products
          %th
          %th 
          - if current_user.admin?
            %th
            %th
      %tbody      
        - categories.each do |category|
          %tr
            %td.col-md-6= category.name
            %td.text-center
              %span.badge= category.products_count
            %td= link_to 'Show', category, class: 'btn btn-info btn-xs'
            %td= link_to 'Products', category_products_path(category), class: 'btn btn-default btn-xs'
            - if current_user.admin?
              %td= link_to 'Edit', edit_category_path(category), class: 'btn btn-success btn-xs'
              %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'

- if current_user.admin?
  .row
    .col-md-4.col-md-offset-4
      = link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/show.html.haml
%p#notice= notice
.row
  .col-md-6.col-md-offset-3
    %p
      %b Name:
      = category.name

    .list
      %ul.list-unstyled
        - category.products.each do |product|
          %li
            = link_to 'Show', category_product_path(category, product), class: 'btn btn-info btn-xs'
            = product.title

%p
  %h3 New product
  = render 'products/form'
- if current_user.admin?
  = link_to 'Edit', edit_category_path(category)
  \|
= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    %nav.navbar.navbar-default.navbar-static-top
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{ :'data-toggle'=> 'collapse', :'data-target' => 'navbar-collapse' }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %span.navbar-brand #{AppConfig.workshops_name}
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            - if current_user
              %li= link_to 'Categories', categories_path
              %li= link_to 'Users', users_path
          %p.navbar-text.navbar-right
            - if current_user
              %strong= link_to current_user.full_name, user_path(current_user)
              = link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-xs' do
                = fa_icon 'user-times', text: 'Logout', right: true 
            - else
              = link_to new_user_session_path, class: 'btn btn-primary btn-xs' do
                = fa_icon 'chevron-circle-down', text: 'Login', right: true
              = link_to new_user_registration_path, class: 'btn btn-primary btn-xs' do
                = fa_icon 'user-plus', text: 'Signup', right: true 
    .container-fluid
      .row
        .col-md-12
          - if flash[:alert]
            .alert.alert-warning.alert-dismissible{role: 'alert'}
              %button.close{:'data-dismiss' => 'alert', :'aria-label' => 'Close', type: 'button'}
                %span{:'aria-hidden' => 'true'} &times;
              %strong Warning!
              = flash[:alert]
              
          - if flash[:notice]
            .alert.alert-success.alert-dismissible{role: 'alert'}
              %button.close{:'data-dismiss' => 'alert', :'aria-label' => 'Close', type: 'button'}
                %span{:'aria-hidden' => 'true'} &times;
              %strong Notice!
              = flash[:notice]

          - if flash[:error]
            .alert.alert-danger.alert-dismissible{role: 'alert'}
              %button.close{:'data-dismiss' => 'alert', :'aria-label' => 'Close', type: 'button'}
                %span{:'aria-hidden' => 'true'} &times;
              %strong Error!
              = flash[:error]
      = yield

app/views/products/_form.html.haml
= simple_form_for [category, product], html: { class: 'form-horizontal' }  do |f|
  .form-group
    = f.label :title, class: 'col-md-3 control-label'
    = f.input :title, label: false, class: 'form-control', wrapper_html: { class: 'col-md-5' }
  .form-group
    = f.label :description, class: 'col-md-3 control-label'
    = f.input :description, label: false, class: 'form-control', wrapper_html: { class: 'col-md-5' }
  .form-group
    = f.label :price, class: 'col-md-3 control-label'
    = f.input :price, label: false, class: 'form-control', as: :string, wrapper_html: { class: 'col-md-5' },
      placeholder: 'Price fromats:  12 or 12.34 or 12.00 or 12,00'
  .form-group
    .col-md-offset-3
      = f.submit 'Save', class: 'btn btn-default'

app/views/products/_info.html.haml
.row
  .col-md-8.col-md-offset-2
    %table.table.table-hover
      %thead
        %tr
          %th Title
          %th Description
          %th Price
          %th Avg Rating
          %th Category
      %tbody
        %td= product.title
        %td.col-md-6= product.description
        %td= product.price
        %td= product.average_rating
        %td= product.category.name

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', category_product_path(category, product)
\|
= link_to 'Back', category_path(category)

app/views/products/index.html.haml
%h1 Listing products

.row
  .col-md-7.col-md-offset-2
    = link_to 'Create new product', new_category_product_path(category), class: 'btn btn-info btn-sm'
    %table.table.table-hover
      %thead
        %tr
          %th Title
          %th Description
          %th Price
          %th Avg Rating
          %th
          %th
          %th
      %tbody
        - products.each do |product|
          %tr
            %td= product.title
            %td.col-md-4= product.description
            %td= product.price
            %td= product.average_rating
            %td= link_to 'Show', category_product_path(product.category, product), class: 'btn btn-info btn-xs'
            - if current_user.is_product_owner?(product)
              %td= link_to 'Edit', edit_category_product_path(product.category, product), class: 'btn btn-success btn-xs'
              %td= link_to 'Destroy', category_product_path(product.category, product), 
                method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'
.row
  .col-md-10.col-md-offset-2
    = paginate products 

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', category_products_path

app/views/products/show.html.haml
= render 'info'

%h3 Add review
= render 'reviews/form'

- if product.reviews.any?
  %h3 Current reviews
  = render reviews
  .col-md-9.col-md-offset-3
    = paginate reviews



- if current_user.is_product_owner?(product)
  = link_to 'Edit', edit_category_product_path(category.id, product.id)
  \|
= link_to 'Back', category_products_path, class: 'btn btn-primary'

app/views/reviews/_form.html.haml
= simple_form_for [category, product, review], html: { class: 'form-horizontal' } do |f|
  .form-inputs
    .form-group
      = f.label :content, class: 'col-md-3 control-label'
      = f.input :content, label: false, class: 'form-control', wrapper_html: { class: 'col-md-5' }
    .form-group
      = f.label :rating, class: 'col-md-3 control-label'
      = f.input :rating, collection: 1..5, label: false, class: 'form-control', wrapper_html: { class: 'col-md-4' }
    .form-group
      .col-md-offset-3
        = f.submit 'Save', class: 'btn btn-default'

app/views/reviews/_review.html.haml
.row.review
  .col-md-5.col-md-offset-3.review_wrapper
    .col-md-12
      .content= review.content
    .col-md-12.footer
      %p
        %b= review.rating
        %em= review.author

app/views/reviews/new.html.haml
%h1 New review

= render 'products/info'
= render 'form'

app/views/users/index.html.haml
%h1 Listing Users
.row
  .col-md-4.col-md-offset-4
    %table.table.table-hover
      %thead
        %tr
          %th Name
          %th Email
          %th Reviews
          %th 
      %tbody      
        - users.each do |user|
          %tr
            %td= user.full_name
            %td= user.email
            %td.text-center
              %span.badge= user.reviews_count
            %td= link_to 'Show', user, class: 'btn btn-info btn-xs'

app/views/users/show.html.haml
.row
  .col-md-11.col-md-offset-1
    %strong= user.full_name
    .h4 About me: 
    = user.about_me
%br    
.row
  .col-md-6.col-md-offset-3
    %table.table.table-hover
      %thead
        %tr
          %th Product
          %th Content
          %th Date
      %tbody
        - recent_reviews.each do |review|
          %tr 
            %td= review.product.title
            %td= review.short_content
            %td= review.created_at.strftime("%d-%m-%Y")    
%br
.row
  .col-md-12.text-center
    Last singned at:
    = user.last_sign_in_at
    From ip: 
    = user.last_sign_in_ip
 
= link_to 'Edit My Account', edit_user_registration_path  